#pragma once

#define REV_ID_HANDLE int
#define REV_ID_NONE -1
#define REV_INDEX_NONE -1

#define REV_D3D_DRIVER_TYPE D3D_DRIVER_TYPE_HARDWARE
#define REV_BACK_BUFFER_FORMAT DXGI_FORMAT_R8G8B8A8_UNORM
#define REV_DEPTH_STENCIL_FORMAT DXGI_FORMAT_D32_FLOAT